"""empty message

Revision ID: 2e89a0bf1ac9
Revises: 
Create Date: 2019-01-17 01:09:29.205800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e89a0bf1ac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'adminlog', 'admin', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'oplog', 'admin', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'order_detail', 'user', ['order_apply_id'], ['id'])
    op.alter_column('role', 'role_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'role', ['role_name'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'userlog', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userlog', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'role', type_='unique')
    op.alter_column('role', 'role_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'order_detail', type_='foreignkey')
    op.drop_constraint(None, 'oplog', type_='foreignkey')
    op.drop_constraint(None, 'adminlog', type_='foreignkey')
    # ### end Alembic commands ###
